baseURL = "https://srmesh.netlify.app/"
languageCode = "en-us"
title = "SR Mesh"
theme = "minimal"

[params]
    author = "Santa Rosa Mesh"
    description = "Official site of the Santa Rosa Mesh Network"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/faq/"
    name = "FAQ"
    weight = 4
    
[[menu.main]]
    url = "/join/"
    name = "Join Us"
    weight = 5

[[menu.main]]
    url = "/map/"
    name = "Map"
    weight = 6

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:srmeshnet@gmail.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/SRMesh/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/username/"
    name = "fab fa-twitter"
    weight = 3
